# Generated by Django 4.2 on 2023-07-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='students',
            field=models.ManyToManyField(related_name='professors', to='app_one.student'),
        ),
    ]
